---
- name: Windows updates
  hosts: all

  tasks:
    - name: Download Patch Report
      ansible.builtin.get_url:
        url: https://{{ general_report_server }}/reports/windowspatch.html
        dest: /tmp/windowspatch.html

    - name: Create a ServiceNow ticket
      servicenow.itsm.incident:
        instance:
          host: "{{ sn_instance }}"
          username: "{{ sn_username }}"
          password: "{{ sn_password }}"
        state: new
        caller: "ansible"
        impact: medium
        urgency: medium
        short_description: "System Updated: {{ vm_name }}"
        description: "Full report: {{ awx_workflow_job_id }}" #https://{{ general_report_server }}/reports/windowspatch.html"
        attachments:
          - path: "/tmp/windowspatch.html"        
